### PR TITLE
Add lemmy docker compose

### PR DESCRIPTION
**Pull request by lil5**
I followed the docker installation documentation
https://join-lemmy.org/docs/en/administration/install_docker.html

A simple `make docker-start` will start a lemmy server to test mlem on.

`make docker-remove` will remove all attributed containers and volumes

### CODE REVIEW

**Comment by buresdv** [comment]
Wrong repo

https://github.com/LemmyNet/lemmy

**Comment by lil5** [comment]
@buresdv No no this is so that contributors can easily get started working on Mlem with a test server

**Comment by buresdv** [comment]
Ooh I understand. There's already an existing test server for Mlem, so I'll add it to the description somewhere. Maybe you could create your own repo with this?

**Comment by ShadowJonathan** [comment]
Mlem's testing server is here; https://test-mlem.jo.wtf/

There's vague plans to add this to the test cases to make mlem test against an actual server, to spare developers the need to run a server like this, but we could maybe revisit it later.

**Comment by lil5** [comment]
https://github.com/lil5/mlem-dev-docker there you go

**Comment by lil5** [comment]
Testing the app with the docker server it's been a perfect combination, fully local development.

Please try it out yourselves

**Pull request closed without merging**
