### PR TITLE
Beautified Account Add View, Tweaked Accounts Page Text

### PR DESCRIPTION
**Pull request by andrew-vanderbilt**
The Account add view has been overhauled for visual appeal. The app icon is placed on the top of the sheet, along with informative text (Account Details). Relabeled form fields and provided context for intended use. Added event handler for onSubmit, along with Log In button below form. Moved spinner to the center of the view, and tweaked text and iconography. Tweaked text on Accounts Page to make need for account more clear. See screenshots in comments below.

### CODE REVIEW

**Comment by andrew-vanderbilt** [comment]
Simulator Screenshot - iPhone 14 Pro - 2023-06-09 at 15 41 24
Simulator Screenshot - iPhone 14 Pro - 2023-06-09 at 15 41 19
94120/941a873f-5c89-4ed7-b1f9-ad257b5cbbd6)
Simulator Screenshot - iPhone 14 Pro - 2023-06-09 at 15 40 51

**Comment by andrew-vanderbilt** [comment]
I see in some places in the code we are using alerts instead of the spinner. Is this preferred?

**Comment by buresdv** [comment]
Thank you for the contribution! I'm hesitant to approve this PR in its current form:
1. I like the new "No accounts added" text, that should stay
2. Fields need to have their labels always visible, as per Apple's HIG: Snímek obrazovky 2023-06-10 v 11 37 12 and the Settings app: IMG_1169
3. When a button is in a List, it should not have a background, again as per the Settings app: IMG_1168 You can align it to the center, but remove the styling.
4. The new progress alert doesn't fit the iOS aesthetic, it looks much more like Android. I think the old progress style, where it was in the sheet header, should return
5. I think that the app icon and the text "Account details" shouldn't be displayed on top of the sheet. It would be shown every time the user wants to add a new account, and it would become tiring to look at the same icon all the time. It also makes the signup sheet more busy, which it shouldn't be, since it just needs to let the user log in and then disappear.

**Comment by andrew-vanderbilt** [comment]
I've integrated the changes you have suggested. Attached is the new look. What do you think?

Simulator Screenshot - iPhone 14 Pro - 2023-06-11 at 10 07 01

Simulator Screenshot - iPhone 14 Pro - 2023-06-11 at 10 06 14

Simulator Screenshot - iPhone 14 Pro - 2023-06-11 at 10 06 15

**Comment by ShadowJonathan** [comment]
Could you soft-reset your commits to the master branch? This way, you're pulling in the new gitignore file, and also removing the extra files that shouldn't be committed.

After this, you should force-push to this branch, but to allow you to restore your files, i'll add a reference to the latest commit: https://github.com/buresdv/Mlem/pull/66/commits/f5bec9b3b15d4466f366b890876407af129bb361

**Comment by ShadowJonathan** [comment]
Could you soft-reset your commits to the master branch? This way, you're pulling in the new gitignore file, and also removing the extra files that shouldn't be committed.

After this, you should force-push to this branch, but to allow you to restore your files, i'll add a reference to the latest commit: [`f5bec9b` (#66)](https://github.com/buresdv/Mlem/pull/66/commits/f5bec9b3b15d4466f366b890876407af129bb361)

**Comment by ShadowJonathan** [comment]
There's still a lot of junk files like .DS_Store and other Xcode stuff

**Comment by andrew-vanderbilt** [comment]
> There's still a lot of junk files like .DS_Store and other Xcode stuff

Sorry, I suck at git. I'm attempting to figure it out.

**Comment by ShadowJonathan** [comment]
No worries

Can you do `git remote -v`?

**Comment by andrew-vanderbilt** [comment]
> No worries
> 
> Can you do `git remote -v`, on the command line, in your project folder?

Yes, I have a list of repos:

github-desktop-justincmoy	https://github.com/justincmoy/Mlem.git (fetch)
github-desktop-justincmoy	https://github.com/justincmoy/Mlem.git (push)
origin	https://github.com/andrew-vanderbilt/Mlem.git (fetch)
origin	https://github.com/andrew-vanderbilt/Mlem.git (push)
upstream	https://github.com/buresdv/Mlem.git (fetch)
upstream	https://github.com/buresdv/Mlem.git (push)

**Comment by ShadowJonathan** [comment]
do `git fetch --all`, then do `git reset --soft upstream/master`

then make a new commit, and then force-push it here

**Comment by buresdv** [comment]
Hmm, I still don't think this looks right. I can't put my finger on it, but this makes me feel of a ported Android app :(

**Pull request closed without merging**
