### PR TITLE
Add Comment.replaceReply and .removeReply

### PR DESCRIPTION
**Pull request by samalone**
I added both Comment.replaceReply() and Comment.removeReply().
removeReply might be handy if someone decides to delete their comment.
Closes https://github.com/buresdv/Mlem/issues/12

### CODE REVIEW

**Comment by buresdv** [comment]
Thank you, does this also work for top-level comments, i.e. those comments with no parentID?

**Comment by samalone** [comment]
Yes, it should work for top-level comments.
Be aware that the replacement can also change the reply's children!
This could be handy, but it could also be surprising.
If you don't want the children to change, be sure the replacement has the same children as the original.

**Comment by buresdv** [comment]
Alright, thanks for the info! This is exactly what I needed 😊

**Review by buresdv — APPROVED** [review]
Looks good

**Pull request merged**
