### PR TITLE
Add iPad to Supported Destinations

### PR DESCRIPTION
**Pull request by thx1766**
Add iPad to Supported Destinations

### CODE REVIEW

**Comment by andrew-vanderbilt** [comment]
Making it a giant iPhone app would be detrimental to the experience of the user. Unless the app undergoes some redesigns to utilize the larger screen real-estate, I fail to see how just enabling the build iPad family target is a benefit.

**Comment by isametry** [comment]
…More detrimental than an upscaled 750px iPhone app surrounded with black bars? This has to be trolling right?

Even if precisely ZERO further enhancements are added to take advantage of an iPad screen, this change singlehandedly takes the app from “unbearable on iPad” to “useable on iPad”.

**Comment by ShadowJonathan** [comment]
Multiplatform support is tracked under #40, this is a PR from an external contributor, please don't act or banter like this is an officially-approved PR yet, as we have yet to review it.

There's been discussion on the best way to do iPad support the last few days, and @thx1766 was a bit eager to send a PR ahead of time.

**Comment by isametry** [comment]
I'm sorry, you're right, this is not the place for discussion. I've stripped the unnecessarily agitated parts from my previous comment.

**Comment by thx1766** [comment]
Here are some screenshots of the current state of Mlem on the iPad, assuming we took the current main branch and deployed it to an iPad.

The first two screenshots are portrait and landscape views of the simulator showing the iPhone-shaped result.

The other images are from my fiancé's physical iPad running multiple apps with Stage Manager. Here Mlem is resizable, but not necessarily ideal.

Simulator Screenshot - iPad (10th generation) - 2023-06-10 at 11 40 44
Simulator Screenshot - iPad (10th generation) - 2023-06-10 at 11 40 21
IMG_9ABB4EDF7EC5-1
IMG_7EBAFDF01532-1
4c5)
IMG_C92E699F2119-1

This last screenshots show the settings tab with nested navigation, which swiftUI renders in a sensible way on iPhone but seems silly and requires extra taps to navigate around on an iPad. If there are a lot of settings that can't be managed on one iPad sized page, it might make sense to group them this way, but it seems like a waste of screen real estate to me. Just my opinion for the design team to take into consideration.
IMG_E6EC40C0DE40-1

IMG_C2CEA96CAFA9-1

**Comment by buresdv** [comment]
Thank you, what if you apply the changes in this PR to the current state of the master branch? How does that look?

**Comment by thx1766** [comment]
Adding the iPad supported destination, we get a much more elegant settings menu.
IMG_AD017CA68A5E-1
IMG_AF0FE96DE023-1

**Comment by thx1766** [comment]
Here's the simulator showing landscape settings page in full screen mode.
Simulator Screenshot - iPad (10th generation) - 2023-06-10 at 11 58 36

**Comment by thx1766** [comment]
Closing this out as this is not a priority currently.

**Comment by buresdv** [comment]
Thank you very much for the pictures, I think that even if we don’t change much, the experience is much better.

Can you please post all these pictures to #42? And we should continue the discussion there.

**Pull request closed without merging**
